package system.design.elevator.enums;

public enum FloorNumber {
    FLOOR_NUMBER_ONE,
    FLOOR_NUMBER_TWO,
    FLOOR_NUMBER_THREE,
    FLOOR_NUMBER_FOUR,
    FLOOR_NUMBER_FIVE,
    FLOOR_NUMBER_SIX,
    FLOOR_NUMBER_SEVEN,
    FLOOR_NUMBER_EIGHT,
    FLOOR_NUMBER_NINE,
    FLOOR_NUMBER_TEN,
    FLOOR_NUMBER_ELEVEN,
    FLOOR_NUMBER_TWELVE,
    FLOOR_NUMBER_THIRTEEN,
    FLOOR_NUMBER_FOURTEEN,
    FLOOR_NUMBER_FIFTEEN;
}
